# Generated by Django 4.2.10 on 2024-03-08 12:57

from django.db import migrations, models
import petstagram.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_petstagramuser_groups_petstagramuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="petstagramuser",
            managers=[
                ("objects", petstagram.accounts.models.PetstagramUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="petstagramuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="petstagramuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
