# Generated by Django 4.2.10 on 2024-02-18 18:41

from django.db import migrations, models
import petstagram.photos.models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petphoto",
            name="photo",
            field=models.ImageField(
                upload_to="pet_photos/",
                validators=[
                    petstagram.photos.models.MaxFileSizeValidator(limit_value=5242880)
                ],
            ),
        ),
    ]
