# Generated by Django 4.2.10 on 2024-03-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_rename_tagged_pet_petphoto_tagged_pets"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photocomment",
            name="to_photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="photos.petphoto"
            ),
        ),
        migrations.AlterField(
            model_name="photolike",
            name="to_photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="photos.petphoto"
            ),
        ),
    ]
