# Generated by Django 4.2.10 on 2024-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
