# Generated by Django 4.2.10 on 2024-03-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pets", "0003_pet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
